config/routes.rb
PutsReq::Application.routes.draw do
  devise_for :users

  root to: 'home#index'

  get ':token/requests_count' => 'buckets#requests_count'
  post 'buckets' => 'buckets#create', as: :buckets
  get ':token/inspect' => 'buckets#show', as: :bucket
  get ':token/last' => 'buckets#last', as: :bucket_last
  get ':token/requests/:id' => 'requests#show', as: :request
  get ':token/requests' => 'requests#index', as: :requests
  get ':token/last_response' => 'buckets#last_response', as: :bucket_last_response
  put ':token/buckets' => 'buckets#update', as: :update_bucket
  match ':token' => 'buckets#record', via: :all, as: :bucket_record
  delete ':token/delete' => 'buckets#destroy', as: :bucket_destroy
  delete ':token/clear' => 'buckets#clear', as: :bucket_clear
  post ':token/fork' => 'buckets#fork', as: :bucket_fork
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    selector = if user_signed_in?
                 Bucket.or([user: current_user], [owner_token: owner_token])
               else
                 Bucket.where(owner_token: owner_token)
               end

    @buckets = selector.order(:created_at.desc).limit(20)

    @buckets.each do |bucket|
      next if !user_signed_in? || bucket.user

      # assign buckets created without login to the current logged user
      bucket.update_attribute :user, current_user
    end
  end
end

app/views/home/index.html.erb
<div class="row">
  <div class="span10">
    <div class="">
      <header>
        <%= image_tag 'logo.png' %>
        <h3><em>PutsReq</em> lets you record HTTP requests and fake responses like no other tool available. Try it now!</h3>
        <%= form_for :bucket, url: buckets_path do |f| %>
          <button class="btn btn-primary btn-large">Create a PutsReq</button>
          <em>
            <% if user_signed_in? %>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to 'Sign in', new_user_session_path  %> | <%= link_to 'Sign up', new_user_registration_path %>
            <% end %>
          </em>
        <% end %>
      </header>
      <section class="start">
        <div class="row">
          <div class="<%= @buckets.any? ? 'col-md-7' : 'col-md-12' %>">
            <h4>Record requests</h4>
            <p>Change your target URL to a PutsReq URL to start recording your requests.</p>
            <h4 class="tm20">Fake responses</h4>
            <p>PutsReq is the easiest way to fake HTTP responses. You can define the response status, headers and body you want using <a href="https://github.com/phstc/putsreq#response-builder">JavaScript</a>.
              <h4 class="tm20">Forward requests</h4>
              <p>You can easily <a href="https://github.com/phstc/putsreq#forwardto">forward requests to another URL</a>, including <a href="https://github.com/phstc/putsreq#cli">localhost</a>.
          </div>
          <% if @buckets.any?  %>
            <div class="col-md-5">
              <div class="history">
                <h4 class="bm0 tm0">History</h4>
                <small>View and manage your buckets:</small>
                <ul class="tm5">
                  <% @buckets.each do |bucket| %>
                    <li><%= link_to "#{bucket.name} (#{bucket.requests_count})", bucket_path(bucket.token) %></li>
                  <% end %>
                </ul>
              </div>
              </div>
          <% end %>
        </div>
      </section>
    </div>
  </div>
</div>