config/routes.rb
PutsReq::Application.routes.draw do
  devise_for :users

  root to: 'home#index'

  get ':token/requests_count' => 'buckets#requests_count'
  post 'buckets' => 'buckets#create', as: :buckets
  get ':token/inspect' => 'buckets#show', as: :bucket
  get ':token/last' => 'buckets#last', as: :bucket_last
  get ':token/requests/:id' => 'requests#show', as: :request
  get ':token/requests' => 'requests#index', as: :requests
  get ':token/last_response' => 'buckets#last_response', as: :bucket_last_response
  put ':token/buckets' => 'buckets#update', as: :update_bucket
  match ':token' => 'buckets#record', via: :all, as: :bucket_record
  delete ':token/delete' => 'buckets#destroy', as: :bucket_destroy
  delete ':token/clear' => 'buckets#clear', as: :bucket_clear
  post ':token/fork' => 'buckets#fork', as: :bucket_fork
end

app/models/bucket.rb
class Bucket
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :forks, class_name: 'Bucket'

  belongs_to :fork, class_name: 'Bucket', optional: true
  belongs_to :user, optional: true

  field :token
  field :name
  field :owner_token
  field :response_builder, default: -> { default_response_builder }
  field :history_start_at, type: Time

  # temporally hack
  attr_accessor :request

  index token: 1
  index owner_token: 1
  index fork_id: 1

  index({ updated_at: 1 }, expire_after_seconds: 1.month)

  before_create :generate_token

  def requests
    # I couldn't make has_many + conditions work with Mongoid
    # requests must be filtered by created_at
    # see clear_history

    Request.where(bucket_id: id).gte(created_at: history_start_at || created_at).order(:created_at.desc)
  end

  def responses
    # I couldn't make has_many + conditions work with Mongoid
    # responses must be filtered by created_at
    # see clear_history

    Response.where(bucket_id: id).gte(created_at: history_start_at || created_at).order(:created_at.desc)
  end

  def clear_history
    # requests and responses are capped collections in production, we cannot delete docs on a capped collection
    # so we filter these objects by the history_start_at to "clear"
    # db.runCommand({ "convertToCapped": "requests",  size: 25000000 });
    # db.runCommand({ "convertToCapped": "responses", size: 25000000 });
    update_attribute :history_start_at, Time.zone.now
  end

  def name
    if (name = self[:name]).blank?
      token
    else
      name
    end
  end

  def last_request
    requests.order(:created_at.desc).first
  end

  def last_response
    responses.order(:created_at.desc).first
  end

  def last_request_at
    last_request&.created_at
  end

  def first_request
    requests.order(:created_at.asc).first
  end

  def first_request_at
    first_request&.created_at
  end

  delegate :count, to: :requests, prefix: true

  private

  def generate_token
    self.token ||= loop do
      random_token = SecureRandom.urlsafe_base64(15).tr('_-', '0a')
      break random_token unless Bucket.where(token: random_token).exists?
    end
  end

  def default_response_builder
    <<-DEFAULT.strip_heredoc
      // Build a response
      var msg = 'Hello World';

      if(request.params.name) {
        msg = 'Hello ' + request.params.name;
      }

      response.body = msg;

      // Forward a request
      // request.forwardTo = 'http://example.com/api';
    DEFAULT
  end
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :record

  before_action :check_ownership!, only: %i[clear destroy update]

  def requests_count
    render json: { requests_count: bucket.requests.count }
  end

  def create
    redirect_to bucket_path(bucket.token)
  end

  def fork
    fork = Bucket.create(
      owner_token: owner_token,
      response_builder: bucket.response_builder,
      name: "Copy of #{bucket.name}",
      fork: bucket
    )

    redirect_to bucket_path(fork.token)
  end

  def clear
    bucket.clear_history

    redirect_to bucket_path(bucket.token)
  end

  def destroy
    bucket.destroy

    redirect_to root_path
  end

  def show
    bucket.request = bucket.requests.page(params[:page]).per(1).first

    respond_to do |format|
      format.html { render }
      format.json { render json: bucket, serializer: BucketSerializer }
    end
  end

  def update
    update_bucket = bucket_params
    update_bucket[:user_id] = current_user.id if user_signed_in?

    bucket.update update_bucket

    redirect_to bucket_path(bucket.token)
  end

  def last
    return render_request_not_found unless last_request = bucket.last_request

    respond_to do |format|
      format.html { render plain: last_request.body }
      format.json { render json: JSON.pretty_generate(last_request.attributes) }
    end
  end

  def last_response
    return render_request_not_found unless last_response = bucket.last_response

    respond_to do |format|
      format.html { render plain: last_response.body }
      format.json { render json: JSON.pretty_generate(last_response.attributes) }
    end
  end

  def record
    result = RecordRequest.call(bucket: bucket, rack_request: request)
    recorded_response = result.response

    response.headers.merge! recorded_response.headers.to_h

    render plain: body_as_string(recorded_response),
           status: recorded_response.status
  end

  private

  def render_request_not_found
    respond_to do |format|
      format.html { redirect_to bucket_path(bucket.token), alert: 'Please submit a request first' }
      format.json { head :not_found }
    end
  end

  def bucket_params
    params.require(:bucket).permit(:response_builder, :name)
  end
end

app/views/buckets/_buttons.html.erb
<button class="btn btn-primary tm10">Update</button>
<%= link_to 'Fork', bucket_fork_path(bucket.token), class: 'btn btn-default tm10 lm5', method: :post %>
<%= link_to 'Clear History', bucket_clear_path(bucket.token), class: 'btn btn-default tm10 lm5', method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Destroy', bucket_destroy_path(bucket.token), class: 'btn btn-default tm10 lm5', method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/buckets/_form.html.erb
<%= form_for bucket, url: update_bucket_path(bucket.token), method: :put do |f| %>
  <%= f.hidden_field :response_builder %>
  <script id="response-builder-container"  type='application/vns.putsreq-response_builder'><%== bucket.response_builder %></script>
  <div class="row">
    <div class="col-md-6">
      <h4>Bucket name
      <small><em>You can change it anytime.</em></small>
      </h4>
      <div class="input-group putsreq-name bm30">
        <%= f.text_field :name %>
        <% if bucket.fork %>
          <p><small>forked from <%= link_to bucket.fork.name, bucket_path(bucket.fork.token) %></small></p>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <h4>Requests
        <small><em>The number of requests made to this bucket.</em></small>
      </h4>
      <div id="request-count-react-root"></div>
    </div>
  </div>
  <h4>Response Builder&nbsp;<a href="https://github.com/phstc/putsreq#response-builder" target="_blank"><span class="glyphicon glyphicon-info-sign"></span></a></h4>
  <div id="editor" name="editor" style="width: 100%; height: 150px"></div>
  <textarea id="response_builder" name="response_builder" style="display:none;"></textarea>
  <p>
    <% if owner?(bucket) %>
      <%= render 'buttons' %>
    <% else %>
      <%= render 'readonly_buttons' %>
    <% end %>
  </p>
<% end %>

app/views/buckets/_readonly_buttons.html.erb
<%= link_to 'Fork', bucket_fork_path(bucket.token), class: 'btn btn-primary tm10', method: :post %>

app/views/buckets/_requests.html.erb
<!-- request id: <%= recorded_request.id %> -->
<div class="panel-group request-show" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <span class="pull-right label label-info"  title="<%= recorded_request.created_at.utc %>"><%= time_ago_in_words recorded_request.created_at %> ago</span>
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Headers
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <pre><%= headers_as_string(recorded_request) %></pre>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <%= recorded_request.request_method.upcase %> <%= recorded_request.path %>
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <pre><%= body_as_string(recorded_request) %></pre>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
          Response
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        <pre><%= body_as_string(recorded_request.response) %></pre>
      </div>
    </div>
  </div>
</div>

app/views/buckets/show.html.erb
<%= javascript_pack_tag 'application' %>

<% content_for :title, bucket.name %>

<ul class="nav">
  <li class="logo"><a href="/"><%= image_tag 'logo.png' %></a></li>
  <li><a href="<%= "/#{bucket.token}/inspect" %>">Inspect</a></li>
  <li><a href="<%= "/#{bucket.token}/last" %>" title="JSON-formatted">Last Request</a></li>
  <li><a href="<%= "/#{bucket.token}/last_response" %>" title="JSON-formatted">Last Response</a></li>
  <% if user_signed_in? %>
    <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to 'Sign in', new_user_session_path  %></li>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
  <% end %>
</ul>

<section class="putsreq-url-box">
  <h3>Your PutsReq URL</h3>
  <div class="input-group putsreq-url">
    <input id="putsreq-url-input" data-bucket-token="<%= bucket.token %>" type="text" value="<%= token_url(bucket.token) %>" readonly="readonly"></input>
    <span id="copy-button" class="input-group-addon hastip clipboard" data-clipboard-target="#putsreq-url-input">
      <span class="glyphicon glyphicon-link hastip"></span>
    </span>
  </div>
</section>

<br/><br/>

<section>
  <h4>Sample Request using cURL</h4>
  <code>curl -i -X POST -d 'name=Pablo' <%= token_url(bucket.token) %></code>
</section>

<hr/>
<%= render 'form' %>
<hr/>

<p id="new-requests-info"><!-- placeholder: New requests found. Load newer requests? --></p>

<div id="react-root">
</div>

<script type="application/json" id="bucket-json">
  <%== BucketSerializer.new(bucket).to_json %>
</script>